### PR TITLE
Added NLP - Sentence Splitter

### PR DESCRIPTION
**Pull request by SundareshSankaran**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/13231254/ContributorAgreement.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
Hi @SundareshSankaran, thanks for another addition. Noticed some unexpected behaviour when I am not using CAS tables for both input and output.

Here is what I did: Ran the step in standalone mode and (on purpose) specified input and output table that are not in CAS. Btw. still have a libname defined that points to the caslib named public (libname mycasdat CAS caslib="public";). But am not using libref public. Yes, trying to break it but doing this to try to help improve the user experience 😉 

The following error and warnings show up in the SAS log:
```
ERROR: Input table caslib is blank. Check if Input table is a valid CAS table.
WARNING: Attempt to delete macro variable INPUTCASLIB failed. Variable not found.
WARNING: Attempt to delete macro variable OUTPUTCASLIB failed. Variable not found.
```

The error message feels like misleading the user. Furthermore, if both the input and output table are not CAS tables, then it would be good to have the user notified of both. Can live with the warnings, although it would be nice to avoid unnecessary warnings that are in your control.

Btw. I know the that About tab and the README file mention something about pre-reqs and mention a CAS session, but they do not mention that both the input and output table need to point to a CAS table. It's not clear to me whether there is a dependency on a libref public to exist and the need for it to point to caslib public. If so, then that should also be explained to the user.

**Comment by SundareshSankaran** [comment]
Hi @snlwih , thanks for these points.  Before pushing code, let me run you the new results to check if this serves the purpose.

1. Regarding the error messages.  Here's the error specified in a case when both input and output tables are 'invalid':

Screenshot 2023-11-03 at 11 32 08

You may notice I've also avoided a warning.

The error messages also work for cases when either table is "invalid":

Screenshot 2023-11-03 at 11 33 12

Screenshot 2023-11-03 at 11 34 10

2. I have provided more details about the need for Public to be mapped, as well as the explicit CAS table reference for input and output ports.

Screenshot 2023-11-03 at 11 51 20


3. I agree with the move to CASUSER instead of Public, but maybe as a future pull request (where I overhaul other steps where I've used Public for similar purposes)?  

Thanks.

**Comment by snlwih** [comment]
Hi @SundareshSankaran, great stuff with screenshots and yellow marker 😃  All looks good, feel free to push.

**Comment by snlwih** [comment]
Is there a specific reason you're not allowing maintainers to edit/collaborate on your pull request? See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork for more details.

There is a really small change in the readme that I could have taken care of as part of the review. The change log should be in descending date order, so latest changes show at top of list.  

I realize that the following is very detailed, but hopefully easy to fix.

I noticed that the error message around libname public is still not capturing all use cases. If the user has defined libname public, but it points to a caslib that is not public, the first part of the error is wrong. It says: 
```
ERROR: The library PUBLIC is not found. A SAS library PUBLIC libref pointing to the Public caslib needs to exist for storing 
intermediate CAS tables. Assign the caslib.
```
Shouldn't the error be something like:
```
ERROR: The library PUBLIC is not defined or does not point to caslib PUBLIC. A SAS library PUBLIC pointing to the caslib PUBLIC needs to exist and will be used for storing intermediate CAS tables.
```

(suggestion) Also when libname public is not defined or not defined "correctly", and the user has input/output tables that are not CAS tables, then the only error they see is about library public. I agree that if a cas session does not exist this should be a "stop further checking and issue final error". But ideally in this scenario the user could be presented with upto 3 errors, which would allow them to fix them all at the same time? (1: libname public not defined properly, 2: input table not cas table, 3: output table not cas table?) Not required, it's more important that error messages are accurate. Can live with the user fixing one thing and then trying to run and getting a second error.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 07NOV2023.

**Pull request merged**
