### PR TITLE
Addressing issue 1-3 - adding new separator - dealing with NLS charac…

### PR DESCRIPTION
**Pull request by stephanweigandt**
…ter correctly by using k-functions - separator detection fix

# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an **X** inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[contributing_agreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/9976314/contributing_agreement.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
11NOV22: Review started. Seems all indenting is lost in the Program part of the step and all code lines are left-aligned. Is that on purpose?

**Comment by stephanweigandt** [comment]
the indenting is corrected now, please check again. Thank you!

**Comment by snlwih** [comment]
Lines containing SAS code are now nicely indented. 
Lines containing comments are mostly nicely indented and seem to follow a consistent pattern, making them easy to read. There are a few comment blocks that do not adhere to that pattern and seem to be fully left-aligned. Not sure if that is an oversight. Any, will merge this pull request now so we can make the enhanced functionality available

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 14NOV2022

**Pull request merged**
