### PR TITLE
DQ -Identify    a new Custom Step

### PR DESCRIPTION
**Pull request by ArnoldToporowski**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an **X** inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X ] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X ] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

[Toporowski Github Contributor Agreement.docx](https://github.com/sassoftware/sas-studio-custom-steps/files/10088668/Toporowski.Github.Contributor.Agreement.docx)

### CODE REVIEW

**Comment by snlwih** [comment]
25NOV22: Starting review.

Very useful functionality. Would it be possible to make some small changes?

1. Noticed that the capitalization for text in labels of UI controls does not adhere to the UI guidelines. Would you mind fixing this? See [docs/UI-guidelines.md](../blob/main/docs/UI-guidelines.md) for more details. (Yes, I know the original DQ custom step you copied this from has many of the same issue, it's on Lorenzo's to-do list to update his contributions 😉  )
    - Labels for Input/Output Table controls
    - Labels for Column Selector controls (1-5) 
    - Labels for New Column controls (1-5)
    - Lables for Section controls (1-5)
2. Would it be possible to provide the data you use in your demo recording?
    - Common approach is to use data in sashelp or sampsio, or if there is no suitable data in those locations then provide the data as a data step with embedded data. See this [README.md in the GeoDistance with rounding contribution](../blob/main/GeoDistance%20with%20Rounding/README.md#usage) for an example.
    - I know it is not in the contribution guidelines yet, but many of the more recent contributions already use this approach. Feel free to reach out to me directly when you need help with this.  
3. For future contributions please use a .txt or .md version of the contributor agreement.

**Comment by ArnoldToporowski** [comment]
Hi Wilbram,
Sure, I can make those changes.
I guess I just submit a new pull request?
Arn

**Comment by snlwih** [comment]
Thanks for updating the labels and embedding the sample data in the readme file.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 30NOV2022

**Pull request merged**
