### PR TITLE
DQ Clustering step added

### PR DESCRIPTION
**Pull request by lorenzotoja**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an **X** inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/9564400/ContributorAgreement.txt)

### CODE REVIEW

**Comment by lorenzotoja** [comment]
I put in this request three custom steps related to data quality: Clustering, match code and standardize

**Comment by snlwih** [comment]
Have started review of **DQ - Standardize** and **DQ - Match Code** step and provided some feedback to Lorenzo.

**Comment by lorenzotoja** [comment]
Changes completed with the suggestions you sent me.

**Comment by snlwih** [comment]
The steps have been updated to use the Port Details capability to define which columns will appear on each output port, so that during usage of a step at design time of a flow, the column structure of the output table is already known. This allows for a user adding subsequent steps on the output port of this custom step and defining their properties without having to have run the custom step node. 

See [Specify Port Details for Input and Output Tables in a Flow](https://documentation.sas.com/?cdcId=webeditorcdc&cdcVersion=default&docsetId=webeditorsteps&docsetTarget=p0ivb4tza0d9man1gj039hg4wmps.htm) in the SAS Studio documentation for more details.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 21SEP2022

**Pull request merged**
