### PR TITLE
Added step for CAS - Generate Unique ID

### PR DESCRIPTION
**Pull request by SundareshSankaran**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/10584024/ContributorAgreement.txt)

### CODE REVIEW

**Comment by Criptic** [comment]
Thank you for your pull request @SundareshSankaran - I have started the review process

**Comment by SundareshSankaran** [comment]
Thanks, @Criptic  for the feedback.  I have : 
1. Replaced the "Unique ID Column" text field with a "New Column" object
2. Removed the copyVars option and noted that all variables get copied over.
3. Adjusted READMEs accordingly.

**Comment by SundareshSankaran** [comment]
Additional - added New column and existing input table columns to output table metadata.

**Comment by Criptic** [comment]
Thank you for adding the output table metadata @SundareshSankaran

**Pull request merged**
