### PR TITLE
add new custom step: NLP - Extract Entities

### PR DESCRIPTION
**Pull request by ArnoldToporowski**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[Toporowski Github Contributor Agreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/13530337/Toporowski.Github.Contributor.Agreement.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
Looking at your SAS code, I wondered why you move the data between CAS and Compute? The kupcase() function is available in CAS, so I think you could do all post-processing directly in CAS. 

So instead of this:

```
data work.POS_ENTITY_EXTRACT (drop= _ComplexTag_ _Attribute_ _Parent_ _Sentence_ _Paragraph_ );
   set casuser.POS_ENTITY_EXTRACT;
run;
data &outputtable1;
   set work.POS_ENTITY_EXTRACT;
   where kupcase(_Role_) contains "NLP"
         &exclude_NounGroup          ; 
run;
```

couldn't you do the following?

```
data &outputtable1;
   /* Use data set drop= option to avoid reading unused columns */
   set casuser.POS_ENTITY_EXTRACT(drop= _ComplexTag_ _Attribute_ _Parent_ _Sentence_ _Paragraph_ );  
   where kupcase(_Role_) contains "NLP"
         &exclude_NounGroup          ; 
run;
```

Not sure how much CAS automatically optimizes, but you might even want to consider putting the where-clause on the set statement as well using another data set option. Here is link to the [current SAS Viya doc for the where= data set option](https://go.documentation.sas.com/doc/en/pgmsascdc/default/ledsoptsref/p0ny9o8t8hc5zen1qn3ft9dhtsxx.htm) This should result in unsed records being skipped while reading data from disk into memory.

**Comment by ArnoldToporowski** [comment]
Yes, that works!  I couldn't get that to work a year ago, and I have had this custom step published in the internal GitLab repository with the following notes:
I could not figure out how to get the where clause to work in the first data step without getting an "Out of Memory" error (something to do with using a where clause on a caslib table?). So did it in two datasteps. If you can find a more efficient way to do this please update the step code. Also, maybe this can all be done in the tpParse action set, but I couldn't figure out how to do that either. Please update the step code if that is possible.

Maybe I just had a coding error.  Or maybe the more recent Viya release works better?
Thanks, it much more efficient this way!

I was also able to implement your suggestion for the "data set where = " option.  The code looks like this now.

data &outputtable1;
   /* Use data set drop= option to avoid reading unused columns */
   set casuser.POS_ENTITY_EXTRACT( drop= _ComplexTag_ _Attribute_ _Parent_ _Sentence_ _Paragraph_
   /* use data set where= option to avoid reading rows not needed */
                                   where = (kupcase(_Role_) contains "NLP" &exclude_NounGroup)      ) ;
run;

I notice that in a flow the output &outputtable1 in the data step always defaults to the WORK library.  Is there any way to get it to go to a caslib by default?

Arn

**Comment by snlwih** [comment]
To answer your question about temporary tables always going to work at the moment: A new feature is in the works to allow the user to specify a target library on the output port of a step. Not sure when that feature will be implemented though.

**Comment by snlwih** [comment]
Here is a code snippet to determine the Active CAS library of the current session, which might come in handy.
```
%put Active caslib: %sysfunc(GETSESSOPT(&_SESSREF_, CASLIB));
```

And a snippet to drop the intermediate table POS_ENTITY_EXTRACT that is created by textParse.tpParse. When you do not specify a caslib in the table.dropTable call, it will use the active CAS library of the current session, so no need to figure out what that caslib is.
```
proc cas;
   table.dropTable / name="POS_ENTITY_EXTRACT"  quiet=true;
run; quit;
```

Could you add this? Also noticed that readme and About tab have typos in release dates. Seems you have mixed up v1.0 and v1.1. Could you fix that as well?

**Comment by ArnoldToporowski** [comment]
Re: Also noticed that readme and About tab have typos in release dates. Seems you have mixed up v1.0 and v1.1. Could you fix that as well?

The v1.0 has a 2022 date (published last year to the internal GitLab).  V1.1 is the first version to be submitted to github.  Should I just remove the v1.0 line since it was never in github?

**Comment by snlwih** [comment]
To summarize: The step now  has been enhanced to do the following:
* doesn't touch the data unnecessary anymore
* issues an error with a self-explanatory message when the input table is not a CAS table, and stops further processing
* dynamically retrieves the caslib associated with a libname pointing to CAS, so does not assume that libref is same as caslib name
* dynamically retrieves active caslib and writes intermediate results table to active caslib
* performs preprocessing on that intermediate results table and writes it to the "table on the output port". So when no table is connected, it writes it to SAS work. When a CAS table is connected it writes it to that table and the data stays in CAS and is not transferred to compute.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 15DEC2023

**Comment by snlwih** [comment]
@ArnoldToporowski , am I correct that the sample data you provided is fake data, and you have the rights to distribute it?

**Comment by ArnoldToporowski** [comment]
Yes, the sample data is fabricated data.  Thanks for asking.

**Pull request merged**
