### PR TITLE
GEO - Shape Files

### PR DESCRIPTION
**Pull request by Stefano86T**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/13744058/ContributorAgreement.txt)

### CODE REVIEW

**Review by Stefano86T — COMMENTED** [review]
changes

**Comment by Stefano86T** [comment]
I have to finish editing the files

**Comment by snlwih** [comment]
Hi @Stefano86T , still have a number of questions:
- Can't you use the out-of-the-box Load Table step to load a table into CAS and promote it? It seems that the Promote Shape step is unnecessarily duplicating that functionality, or did I miss something.
image
image

- In the Promote Shape step (and maybe in one of your other  steps), you seem to assume that when a library uses the CAS engine, the caslib has the same name as the libref. You cannot rely on that. So you should use the dictionary.libnames table to look for the libref and then retrieve the name of the associated caslib and use that name when generating SAS code that requires the actual caslib name, like in a proc casutil where you use the incaslib= option.
```sas
proc sql;
   /* sysvalue contains the name of the caslib when librefs are using the CAS engine */
   select sysvalue from dictionary.libnames
       where upcase("<libname-goes-here>") and upcase (sysname)="CASLIB";
quit;
```

Most (if not all) steps in the repo that interact with CAS and need the name of the caslib, use that logic. The macro variables generated for an inputtable or outputtable control, include a _engine (like &inputtable1_engine) that you can use to determine whether the libname uses the CAS engine, and can then use the proc sql shown above (with :into mymacrvar) to retieve that caslib name and store it in macro variable.

Hope this helps.

**Comment by snlwih** [comment]
@Stefano86T , noticed that all your step files and your readme still had a DEC2023 last updated date, so took the liberty to updating all of those to 06FEB2024 the date of the last update on your pull request (long live Notepad++ Find in Files (and replace) 😄

**Comment by snlwih** [comment]
The step files were stored on SAS Compute, causing a different structure to be used for the .step files compared to step files storedin SAS Content. As all the other step files in the repo were the result of a download from a SAS Content folder, we use that format in the repo. To conver the structure the following was done:

- In the source system open the .step file from a directory on SAS Compute, this will open the Step Designer
- In the Step Designer use Save As to store it in a SAS Content folder
- From the Explorer panel download the step file from that SAS Content folder
- Include those step files in the GitHub Pull Request

**Pull request merged**
