### PR TITLE
Adding Document Analysis Steps

### PR DESCRIPTION
**Pull request by nadolsw**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

[ContributorAgreement-nadolsw.txt](https://github.com/user-attachments/files/17283801/ContributorAgreement-nadolsw.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
Set DCO Check to pass as there is signed contributor agreement and none of the answers in the initial comment raise any red flags.
@Criptic , as you provided offline feedback to the contributor, could you review the update?

**Comment by snlwih** [comment]
@Criptic , any progress? Am I correct in assuming that you've provided feedback offline and are waiting for the contributor?

**Comment by snlwih** [comment]
Hi William (@nadolsw ), had a quick look at the latest update to this pull request and noticed the following:
* readme (still) contains links to SAS internal doc site.
* readme should contain doc links that use "default" in the URL so it always resolves to the latest production release (so replace  .../v_xxx/... with .../default/...) 
* one of the .step files has a new file name that adheres to naming convention, but the metadata in the json itself still uses the old name. To rename a step you have to rename the step in Explorer panel in the SAS Studio UI. Simply renaming the .step file as OS-level does not work.

Haven't looked at the .step files themselves. I'm assuming that David has made you awaare of UI Guidelines and Coding Best Practices, and use of About tab in the step as explained in the CONTRIBUTING .md file.  

Btw. the CONTRIBUTING.md file contains pointers to the UI guidelines, coding best practices, and mentions _template.step as an example that touches on many of these. 

Can you confirm that all this has been applied to your step files?

**Comment by snlwih** [comment]
@nadolsw , had very quick look at both .step files and noticed the following:
* the "Produce Usage Report Output" step seems to be the original step. Did something go wrong with pushing your update into the pull request? 
   * It has no About tab
   * UI labels are not following the guidelines
 * the last updated date in the About tab of  your steps should be in sync with the last updated date mentioned in your readme

**Comment by Criptic** [comment]
@snlwih working through the updates at the moment and will be posting a summarized feedback here

**Pull request closed without merging**
