### PR TITLE
Add step: CV - Create Object Detection Table

### PR DESCRIPTION
**Pull request by neelan29**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
[Contributor_Agreement_NV.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/14465739/Contributor_Agreement_NV.txt)
   - [ ] My contribution includes encryption or other export-controlled technology

### CODE REVIEW

**Comment by Criptic** [comment]
Thank you for the contribution  @neelan29 
Here are a couple of notes on your contribution:
- Please change the page IDs to start with the prefix page
- For the output table please change the label to Output CAS table
- You are using the .format to have string templates, the more Pythonic way is using f-string
- Please make sure that you can handle files from SAS Content and SAS Server or if only one works create an appropriate error
- Please ensure that you get the actual caslib name, don't use the SAS Studio reported value

**Comment by snlwih** [comment]
@neelan29 , have included some tips below to help  you address some of the feedback provided by @Criptic 

- **From entry: Import - Extract Table from PDF**

```
/*-----------------------------------------------------------------------------------------*
   This block of code checks whether the user has selected a PDF from within the filesystem,
   and not from SAS Content. The name of the file is obtained and stored inside a macro 
   variable.
*------------------------------------------------------------------------------------------*/

%let storageType=%upcase(%scan("&fileName.",1,":"));

%if "&storageType."="SASSERVER" %then %do;
   data _null_;
      call symput("fileNamePDF",scan("&fileName.",2,":","MO"));
   run;
%end;
%else %do;
   %put ERROR:Select a PDF file from the filesystem.;
   data _null_;
      abort exit 123; /* See SAS doc for abort statement , return codes 0-6 are reserved by SAS */
   run;
%end;
```

- **From entry: CAS - Submit Python and R Code**

```
* sprc is short for submit Python and R code;
* Macro to check if the connected tables are in CAS;
%macro _sprc_check_for_engine(_sprc_current_table_engine, _sprc_current_table, _sprc_cfe_rc, _sprc_expected_engine=CAS);
	%local _sprc_current_table_engine
		_sprc_current_table
		_sprc_expected_engine
		_sprc_cfe_rc;

	%if &_sprc_current_table_engine. NE &_sprc_expected_engine. %then %do;
		%let &_sprc_cfe_rc. = 0;

		data _null_;
			putlog "ERROR: The table &_sprc_current_table. is not a &_sprc_expected_engine. table.";
			putlog "ERROR: In order for this step to run your data needs to be loaded in &_sprc_expected_engine.";
			abort 123; /* See SAS doc for abort statement , return codes 0-6 are reserved by SAS */
		run;
	%end;
%mend _sprc_check_for_engine;

* Macro to get the caslib name of the libname;
%macro _sprc_get_caslib_name(_sprc_libref, _sprc_caslib_variable);
	%local _sprc_libref
		_sprc_caslib_variable;
	
	proc sql noprint;
		select sysvalue into :&_sprc_caslib_variable. trimmed from dictionary.libnames
		where libname = upcase("&_sprc_libref.") and upcase(sysname)="CASLIB";
	quit;
%mend _sprc_get_caslib_name;
```

**Comment by snlwih** [comment]
@neelan29 , assuming that CV stands for Computer Vision, I would consider using that in the name of the step. Or at least use the  full phrase and its abbreviation in the first paragraph of both readme.md and About tab.

**Comment by snlwih** [comment]
@neelan29, I noticed that your pull request now contains a step that has been updated. But it still has a number of issues or introduced a number of new issues: 
- Label for object codt_op_table_name should end with a colon (I noticed that in David's comment somehow the colon disappeared. This should be easy to fix)
- Although validation of selections made in the UI are now validated, your codegen uses two different patterns to do so. One approach is to put the error text in the log using %put statements, followed by a data _null_ step with abort 42. The other approach is to put the error/warning text in the log inside the data _null_ step using putlog statement. Could you please consolidate into a single approach? Consistency is an important contributor to ease of understanding code.
- Although the step now has some code to check that a libref is pointing to a caslib, the code is incorrect and assumes that the name of the libref is the same as the name of the caslib. Many users assign those libnames using `libname mydata CAS caslib="a-name-that-is-not-mydata";`. Please use the ..._engine macro variable and check whether it contains the string "CAS" and if so, it actually is pointing to a caslib. Retrieving the name of the caslib can then be done using the dictionary tables. I admit that the macro that was provided earlier was perhaps too generic. So here's some code you could use (and test) 
 
 ```


cas;
libname mycasdat CAS caslib="casuser";
/***
  The following macro variables are generated by the custom step 
  framework for a control of input/output table, given that the user
  has selected mycasdat.class:
***/
%let inputtable1=mycasdat.class;
%let inputtable1_engine=CAS;
%let inputtable1_libref=mycasdat;

/************ Code for use in custom step check ************/

/* Assume the selected table is in a table control with ID inputtable1 */
%global _usr_nameCaslib;
%if "%upcase(&inputtable1_engine)" ne "CAS" %then %do;
   data _null_;
      put "ERROR: The selected table is not a CAS table.";
      put "ERROR: Please select a library that points to a caslib.";
      abort 42;
   run;
%end;
%else %do;
   proc sql noprint;
      select sysvalue into :_usr_nameCaslib trimmed from dictionary.libnames
      where libname=upcase("&inputtable1_libref") and upcase(sysname)="CASLIB";
   quit;
   %put CASLIB name: &_usr_nameCaslib;
%end;
```
- Your Python code seems to reference SAS macro variables that are not created by the custom step framework nor by your code? Eg. in line 136: output_caslib      = SAS.symget("_codt_caslibvariable"?

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 23JUL2024

**Pull request merged**
