### PR TITLE
bugfix - step: Data Ingestion Auto Pilot DIAP

### PR DESCRIPTION
**Pull request by stephanweigandt**
…nternal directory variable to handle very deep directories (from 1024 to 4096),  deal with weird characters in filenames (~#) and replace default separtor from # to |

# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[ContributorAgreement.txt](https://github.com/user-attachments/files/17381488/ContributorAgreement.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
Adding @semioticrobotic from the SAS Open Source Project Office to keep me straight.

@stephanweigandt , there is nothing for you to do. 

Yes, that DCO check is new, but it is an FYI only. The industry standard seems to be to have your commits configured to always sign every commit, and that is what that DCO check looks for. You can configure your environment to automatically do this. Good news is that as a maintainer, I can manually override and set the outcome to "OK". And I'll do this when the signed Contributor Agreement has been attached and the questions in the contribution form haven't raised any red flags :smiley:

@semioticrobotic has provided a pull request in this repository that should make the DCO check less aggressive. But still need to understand the full implications before accepting it. Will make that a priority.

**Comment by snlwih** [comment]
And have jsut set the DCO check to pass. Will now look at the contents of the pull request itself.

**Comment by semioticrobotic** [comment]
I've nothing to add, @snlwih! You've got it all straight. Thanks for the heads-up.

**Comment by snlwih** [comment]
@stephanweigandt , wondering what made you decide to call this a major new version and go from 4.1.2 to 5.0.0? The change log does not seem to indicate anything that would reqiore a major new version number. Why did't you use 4.2.0, what did I miss?

**Comment by stephanweigandt** [comment]
Changing the separator doesn’t make it backward compatible. I thought because of that I have to make it a major version change? Or would 4.2 be sufficient?On Oct 17, 2024, at 12:25 AM, Wilbram Hazejager ***@***.***> wrote:﻿
@stephanweigandt , wondering what made you decide to call this a major new version and go from 4.1.2 to 5.0.0? The change log does not seem to indicate anything that would reqiore a major new version number. Why did't you use 4.2.0, what did I miss?

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 18OCT2024

**Pull request merged**
