### PR TITLE
New custom step:  Loop Deployed Object

### PR DESCRIPTION
**Pull request by x7rtfgj4**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[ContributorAgreement - Remco Gooijer.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/14094114/ContributorAgreement.-.Remco.Gooijer.txt)

### CODE REVIEW

**Comment by x7rtfgj4** [comment]
The latest development contains:
- Added UTF8 support.
- Removed a small bug
- Updated the readme.md file.

**Comment by snlwih** [comment]
@x7rtfgj4 , looks good but noticed that some small changes in the UI are needed so it adheres to the defined UI guidelines and follows pattern defined in  _template.step.

- Labels of table controls need to end with colon. Even if those labels are not visible when used in Flow mode, they are being displayed when using the step in Standalone mode. Btw. you also have a numeric stepper and a text field control that are missing these colons.
- The name of the Tab with descriptive info about the step and its version number and release date should be called "About".
- The info in the About box should follow the pattern defined in the About tab of _template.step
   - So first line is the name of the step, followed by a line of equal signs that is as long as the first line.
   - Change log at the bottom of the About tab. You might not need to list all the previous releases as they were never published to GitHub. Or simply list them as "release 1.0 - release 1.6: never released externally", or something like that. Others have done that as well. 
   - This part is just a FYI: If you have a large amount of info in the About tab, divide the info into logical sections and add a section control for each of them. You can then decide which sections are collapsed by default, probably most of them should be collapsed.  

I would change the first paragraph of your readme and use phrase you have in the About tab, but add a (sub) sentence to mention that the step supports both deployed objects stored on the file system and stored in SAS Content. And when referring to SAS Content, please use that exact same capitalization.

**Comment by x7rtfgj4** [comment]
p.s. The name of the custom step is 'Loop Deployed Object'

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 25MAR2024.

**Pull request merged**
