### PR TITLE
CAS – Convert Char to Varchar

### PR DESCRIPTION
**Pull request by itacrp**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
   
[ContributorAgreement.CarloPetti.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/10758048/ContributorAgreement.CarloPetti.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
This is a continuation of pull request: #40, but now using a different name for the step.

**Comment by snlwih** [comment]
@itacrp, I see lots of unexpected characters in the readme. Guess you ran into the gotcha of using copy/paste from an Outlook message where dashes are "auto-corrected" by Microsoft to a special character that doesn't render properly in Markdown.   Similarly, windows bullet chararacters do not render properly in MarkDown.

I'm pretty sure this really was an oversight, but just in case here is a link to a [GitHub Markdown Basic Formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). 

Regarding custom step UI:
 - The labels for each of the controls in the UI still do not end with a colon as described in [UI-guidelines.md](https://github.com/sassoftware/sas-studio-custom-steps/blob/main/docs/UI-guidelines.md). Could you fix this?
- I would recommend changing the label for the Column Selector from "Index" to "Select columns to use for index:" or perhaps even "(Optional) Select columns to use for index:"
- While you are editing your custom step could you also change "Ver 1.0 (08Feb2023)" to "Version 1.0 (08Feb2023)" in the About tab?

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 17FEB2023

**Comment by itacrp** [comment]
Hi Wilbram,
in the public repository I see also the CS with old name (the previous Pull request).

***@***.***


Carlo


From: Wilbram Hazejager ***@***.***>


Sent: venerdì 17 febbraio 2023 17:06
To: sassoftware/sas-studio-custom-steps ***@***.***>
Cc: Carlo Petti ***@***.***>; Mention ***@***.***>
Subject: Re: [sassoftware/sas-studio-custom-steps] CAS – Convert Char to Varchar (PR #44)


EXTERNAL

Merged #44<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fsas-studio-custom-steps%2Fpull%2F44&data=05%7C01%7Ccarlo.petti%40sas.com%7C7278543c93354e6cc12208db1100e5b6%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C638122467770243016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WCd95%2BOivnQmAiFUJQojgk5UM4Gh01FP25VP2XPEsR4%3D&reserved=0> into main.

**Comment by snlwih** [comment]
@itacrp, I should have checked that again before I merged. I thought that in a previous version of this same pull request I had seem that you had deleted the UT -… files and the files showed up with a red checkmark indicating that they had been deleted. But on further inspection it seems I must have dreamed this.

Could you please do the following for me?
- Sync your fork (so you have the latest)
- Delete the **_UT - Load CAS with VarChar_** Folder and its content
- Issue a new pull request and call it:
   - Removed - Load CAS with VarChar as it is outdated. Replaced by CAS - Convert Char to Varchar

This so it is all documented in pull requests. Of course, as a maintainer I could quickly simply delete the directory and its content, but I’d prefer to have it all done by the “originating contributor” and documented in pull request.

Btw. do you see further up in the Conversation tab in the GitHub webUI how replying in Outlook to GitHub notification emails results in extremely long (and ugly) entries in the conversation thread?  Guess there's not much we can do about this, this is probably caused by Microsoft Exchange/Defender and SAS' configuration. Therefore, I prefer to type my replies in the GitHub webUI itself :-) 

Once the pull request is in, I will add a comment to this thread to link to that new pull-request, closing the (doc) loop :-)

**Comment by snlwih** [comment]
Removal of the old version of step with an old name was done in pull request: #48

**Pull request merged**
