### PR TITLE
New step: Download Job Execution Log

### PR DESCRIPTION
**Pull request by x7rtfgj4**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

[ContributorAgreement - Remco Gooijer.txt](https://github.com/user-attachments/files/17410102/ContributorAgreement.-.Remco.Gooijer.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
Set DCO check to "pass" as there is a signed contributor agreement and none of the answers in the initial comment raised a red flag.

**Comment by snlwih** [comment]
@x7rtfgj4 , thanks for another contribution.

Have made some quick and small changes and have pushed those into the pull request. All related to our published guidelines:
* Changed the layout of the Change Log in your readme to use bullets and indents, similar to what you already had in your About tab and what is in the _template.
* Have %mend statements include the macro name. Makes it easier to figure out context when looking at macro definitions that span  multiple pages on screen.

Have some concerns though:
 * codegen
   * If I'm not mistaken your codegen assums the user to have selected a folder on the SAS Compute file system, but the UI of the step does not inform the user about this pre-req. It should also provide a user-friendly error when the user has selected a SAS Content Folders.
      * You can do this by checking the first part of the string returned by the UI control and check for "sasserver" if I'm not mistaken. If it is not that string then run a data _null_ step with putlog "ERROR: Please select a location on the SAS Server. SAS Content folders are not supported by this custom step", followed by an abort statement in the data step. This will result in the step at runtime be put in error mode. This mjeans that a red cross overlay icon is shown on the node and when the user hovers over the node the "ERROR: ..." text is shown in a popmenu.
    * You overwrite the contents of macro variable returned for UI control _targetdirectory. 
      * Although that does not cause any errors, more clean code would be to extract the info you need in your own macro variable (and remove the variable at the end of your step). What about naming the UI control: _targetlocation and then extract the info in your user-defined _targetdirectory. ?
 * The description section in readme and About tab should probably talk about something like  "... user-defined physical location ***on the file system of the SAS Viya Compute server***...". Many users will  probably be confused by "Download" without further explanation and might think you are talking about the file system of the machine where their web browser runs.

**Comment by x7rtfgj4** [comment]
Hi Wilbram,

Thanks for your feedback!!

All suggestions have been implemented!

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 04NOV2024

**Pull request merged**
