### PR TITLE
Updated Generate Airflow DAG

### PR DESCRIPTION
**Pull request by nicrobert**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[Contributor.Agreement.nicrobert.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/13879966/Contributor.Agreement.nicrobert.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
@nicrobert , great that you added new capabilities.

Made a tiny change to the readme file so the release date syncs up with the release date mentioned in the About tab of the steps.

Noticed that the readme mentions an Airflow version. Is that a pre-req for the custom steps or is that to indicate with which version of Airflow it was tested?

If it is a pre-req then we should mention this in the About tab of each step, and you could do this by explicitly mentioning the Airflow version required, or providing a link to the README file in the repo. Not 100% sure if the Link UI control has already been released, otherwise you might want to consider using that.

**Comment by nicrobert** [comment]
Hi @snlwih ,
It doesn't mention an Airflow version, does it?
It does mention a SAS Airflow Provider Release, which can be interpreted as the required version (in reality, depending on added capabilities, it might not always be the case, but let's keep simple and say this is the required version).
I'll clarify that in the next update that is coming soon.

**Comment by snlwih** [comment]
You're absolutely right, it says "SAS Airflow Provider Release". As many users will see that for the first time, I would strongly recommend to make that explicit by adding a Requirements section in the readme (just like all the other contributions) and list the SAS Studio release, the SAS Airflow Provider release, and the Airflow release.   Btw. just did that. Will merge now.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 18JAN2024.

**Pull request merged**
