### PR TITLE
New Custom Step: LLM - Azure OpenAI RAG

### PR DESCRIPTION
**Pull request by SundareshSankaran**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

### CODE REVIEW

**Comment by SundareshSankaran** [comment]
[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/14654120/ContributorAgreement.txt)

**Comment by samiulhq** [comment]
[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/14655118/ContributorAgreement.txt)

**Comment by snlwih** [comment]
@SundareshSankaran , had a quick look at your step.

Interesting to see that you have most of your Python code embedded in a data _null_ step and then write it out to a temporary external file and then call proc python infile=.

Noticed two controls that have a small issue in the UI:  controls textSource and temperature are missing a colon at the end of its label. Could you fix this? I will then merge it.

**Comment by SundareshSankaran** [comment]
Hi @snlwih , thank you.  I have fixed the two controls.  

Regarding the use of a DATALINES block to embed Python code, yes, perhaps it wasn't apparent earlier, but I've been following this pattern from the ["Hydrate a Chroma DB"](https://github.com/sassoftware/sas-studio-custom-steps/tree/main/Vector%20Databases%20-%20Hydrate%20Chroma%20DB%20Collection) custom step onwards (whenever a step required the use of Python).   

 I do this mostly so that I'm able to call the Python code within a macro.  The other, minor advantage is that Python and SAS code are kept apart as much as practically possible, making them easier to maintain, and a little easier on the eye.

**Comment by snlwih** [comment]
@SundareshSankaran , thanks for quickly fixing that.

**Comment by snlwih** [comment]
@SundareshSankaran , noticed that you didn't update the release date to today. So did that for you both in README.md and About tab of .step file.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 13MAY2024

**Pull request merged**
