### PR TITLE
Add step GX Execute Rules

### PR DESCRIPTION
**Pull request by kotiang54**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
   
[Contributor_Agreement_Stephen.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/12599922/Contributor_Agreement_Stephen.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
Hi @kotiang54, 

Thank you for you contribution. Here is my feedback.

I have modified the title of the pull request to be constistent with the name of the custom step. 

Have some suggestions for change:
- Could you rename your step so it uses the same prefix as the steps in https://github.com/sassoftware/sas-studio-custom-steps/pull/90? This so this Great Expectations related steps show up next to each other in the steps panel
- Could you add an About tab in the step with a description of what the step does (from your readme), list prereqs, and version history. The steps in the above mentioned pull request can be used as an example.

Thanks,
Wilbram

**Comment by kotiang54** [comment]
Hi Wilbram,

I have made the proposed changes and committed them. Take a look at them and let me know how they look.

Thanks.
Stephen.

**Comment by snlwih** [comment]
@kotiang54 , can you confirm that the .csv file with Yellow Taxi Trip Data that you have included in your pull request, can be distributed by SAS? In case it can be distributed does the "owner" of the data require acknowledgement of owner/source of the data?

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 19OCT2023

**Pull request merged**
