### PR TITLE
New Steps: SAS Content - Obtain Folder URI & SAS Content - Create Folder

### PR DESCRIPTION
**Pull request by SundareshSankaran**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/13552438/ContributorAgreement.txt)

### CODE REVIEW

**Comment by SundareshSankaran** [comment]
I apologise for the non-standard submission (namely, two custom steps folders in one pull request), but felt that since these two steps share many common features, and due to the close nature in which they originated, we may consider them as part of the same custom step.  Happy to reconsider if necessary.  Thanks.

**Comment by snlwih** [comment]
Hi @SundareshSankaran, agreed that both steps are closely related and small in terms of UI and codegen, so it's okay to put them in a single pull request.

Here's my feedback, just some (small) text changes to help explain what the steps do. Hope you don't mind.

- **SAS Content - Create Folder**
  - "desired" feels strange in this context. Here are some of my recommendations for changing this:
      - label of textControl "folderName": _Specify name for new folder to create inside selected parent folder:_
         -  I'm okay with an abbreviated version as well, like: _Specify name for new folder to create:_
      - Proposed text for README.md and About tab: 
               _This is a utility custom step which allows you to create a new folder inside a SAS Content folder programmatically. 
               Some SAS programs require operations to be performed on folders inside SAS Content, which is 
               a file_ **_service_** _and not a mounted file system on SAS Compute, therefore you cannot use the dcreate()
               DATA step function and have to use the Viya folders service (REST API)._

- **SAS Content - Obtain Folder URI**
  - "desired" feels strange in this context. Here are some of my recommendations for changing this:
   - Proposed text for README.md and About tab:
           _This is a utility custom step which obtains the URI of a selected SAS Content folder and ..._


On a side note (Feel free to ignore this one):
 - You named your macro to retrieve the folder URI  _**obtain**_sas_content_folder_uri instead of _**get**_sas_content_folder_uri. Using "get" would align with general programming best practices, any specific reason to divert from that best practice?

**Comment by snlwih** [comment]
DId some quick tests, here are my results. Would it be possible to fix these? 

 - **SAS Content - Obtain Folder URI**
    - Screenshot in README.md suggests that the SAS log contains the value of targetFolderURI. But I couldn't find it. Macro variables are being created but the %put statements to print their values in the log (very useful) are not. Could you add these again?
    
 - **SAS Content - Create Folder**
    - When the selected parent folder is a read-only folder, a scary HTTP 403 message is dumped in the log and the step is put in error state. I saw that the [doc on developer.sas.com](https://developer.sas.com/apis/rest/CoreServices/#create-a-new-folder) doesn't explicitly mention 403 (HTTP Forbidden). So don't know whether you can rely on a 403 representing that the user does not have update access and then catching this and issuing a "user-friendly" error message. You might want to check with Joe Furbee on this. 
    - I tried typing in the field that represents the input folder and when I enter sascontent:/, the specified new folder is not created and I also don't see an error. The log says "404 Not found". Should this not be reported as an error to the user, and the step be set in error state?

**Comment by SundareshSankaran** [comment]
Hi @snlwih ,

Slightly different situation with a read-only folder, I’m unable to replicate the **exact** error situation.  

My thoughts on what definitely is, and could be a read-only folder:  

For a non-admin user1,  the folder /Users/viya_admin (and any subfolder thereof) is not even visible, because user1 is not authorized to even know about it.   The error produced in such a case seems to make sense (note that this is a new error while addressing your second point, and therefore you may have not seen it).  I can add "...does not exist or may not be accessible".

Screenshot 2023-12-15 at 15 17 50


The closest alternative I thought of was a folder such as Users for user1, where user1 can’t perform operations even though they can perform operations within /Users/user1.  Here, **I do get a 403**, but it’s not scary in the sense that I’m permitted to carry out further successful operations and the session doesn’t hang.   

Screenshot 2023-12-15 at 15 27 29

Screenshot 2023-12-15 at 15 27 52

I can get in touch with Joe anyways, but currently I’m wondering if my action should be to treat it as another failure mode with a message of “This operation is forbidden.  Check if you have the correct authorization levels and permissions on parent folder &sasFolderPath. “ ?

**Comment by SundareshSankaran** [comment]
Hi @snlwih ,

Further to above, I've pushed changes for:

**SAS Content - Obtain Folder URI**

- Macro variables now show up in the log.

Screenshot 2023-12-18 at 12 51 51


**SAS Content - Create Folder**

- I checked with Joe Furze offline and he concurs with the proposed message indicating that the operation is forbidden and the user might need to check permissions on the asset.  Taking this, and my earlier comment into account, here are some depictions of how different situations are handled.

   - If all goes well

Screenshot 2023-12-18 at 12 54 38

   - if the root folder (your second comment) is provided, treating this as a special case

Screenshot 2023-12-18 at 12 54 38


   - If nothing is provided

Screenshot 2023-12-18 at 12 55 27

   - If the path is improper (or the user makes a wrong assumption on the starting point).  Note that there's a soft warning provided by the UI in such cases too.

Screenshot 2023-12-18 at 12 55 27

   - As discussed with Joe, if a user tries to write to a read-only / any parent where they don't have sufficient rights

Screenshot 2023-12-18 at 13 00 35


-  An edge-case following upon my previous comment: If the user tries to write to a folder that they do not see.  Note that earlier, this special case was concealed within an error scenario of "Folder is not found" which might have covered more benign error situations (e.g. folder was not found because it simply does not exist).  This way, both cases are treated as separate

Screenshot 2023-12-18 at 13 00 59

**Comment by SundareshSankaran** [comment]
I had provided the wrong screenshot earlier for this particular error scenario.  Somehow the previous comment edits do not reflect, hence re-pasting.

If the path is improper (or the user makes a wrong assumption about the start of a path). Note that there's a soft warning provided by the UI in such cases too.

Screenshot 2023-12-18 at 12 55 48

**Comment by snlwih** [comment]
* Fixed incorrect rendering of nested numbered lists in one of the readme files
* Updated release date to reflect the last time the .step files were touched (18DEC2023)

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 20DEC2023

**Pull request merged**
