### PR TITLE
Added Custom Steps for Cloning Git Repo and Deleting Local Repo

### PR DESCRIPTION
**Pull request by SundareshSankaran**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an **X** inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/10558731/ContributorAgreement.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
@SundareshSankaran, thank you for another two contributions :-) Great that you are using "default" in the doc links in your readme files, so they always point to the latest SAS Viya documentation! Also very useful that you've added an overall "category" page that lists the various Git-related steps that are (will be) in the repo. 

I have a few suggestions though. Hopefully they're quick and easy to implement:

- Could you fix the capitalization in labels for UI controls in both custom steps, so they adhere to the [UI-Guidelines](https://github.com/sassoftware/sas-studio-custom-steps/blob/main/docs/UI-guidelines.md) and are consistent with out-of-the-box provided steps in SAS Studio? 
- Could you rename "Git - Clone **_a_** Git Repo" to "Git - Clone Git Repo"? Removing "**_a_**" will make it consistent with the naming approach for your other step. 
- You are referencing GitHub and GitLab in your .md files, and maybe in the About box, with various capitalization approaches, could you fix this to use the official company/product spelling? Of course, when part of a URL spell it using all lower case. 
- Any thoughts about having the readme for "Git - Delete local repo", link back to your "category" page?

**Comment by SundareshSankaran** [comment]
Hi @snlwih , thank you for the suggestions.  I have incorporated the same and committed.

**Comment by snlwih** [comment]
Noticed that the label for the status_table outputtable control still wasn't adhering to UI Guidelines, so quickly fixed that.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 02FEB2023

**Pull request merged**
