### PR TITLE
Add new step: HTTP Request

### PR DESCRIPTION
**Pull request by sukckn**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [x] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [x] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [x] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[Contributor Agreement.txt](https://github.com/user-attachments/files/17162881/Contributor.Agreement.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
Hi Clemens, thanks for another contribution. Looks like a very powerful step which provides the majority of the capabilities provided by proc http. And with lots of user control and beautifully formatted and commented code. Kudos!

Here is my feedback: 
  * UI - Tab: Input Options
    * Checkbox "Use SAS Internal Viya API"
      * The label confused me. My first thought wsa that it meant to indicate that it was a SAS "internal" API, so not publicly documented API, and perhaps your codegen did special handling for this.
      * Only after reading the doc, I understood that this is used to indicate to your codegen that the URL field contains a relative URL (pointing to a SAS Viya service in the deployment). Guess you provide this checkbox, so you do not need to do extensive parsing to figure that out yourself. Right? ;-) 
      * So would be using the label "Above specified URL is a relative-URL and points to a SAS Viya service"? I know verbose, but thought it describes better what it actually is. And hopefully helps the user understand this easier without having to read the doc? It might then be an idea to rename the checkbox control as well (isRelativeURL maybe?) and slightly update the related explanation in the README as well. Just a thought.
      * I see that your codegen relies on macro variable baseURL. Not sure if that is an "undocumented" macro variable that is generated by SAS Studio pre-amble code. Did you know that there is a  documented system option that provides you with the BaseURL for SAS Viya services? See https://go.documentation.sas.com/doc/en/pgmsascdc/default/lesysoptsref/p191674k3chjf3n1vze4cfzfn18e.htm
      * A construct that you see in almost all custom steps in the repo that interact directly with SAS Viya services use something like this to retrieve the URL: 
        ```%let viyaHost=%sysfunc(getoption(SERVICESBASEURL));```
      * @Criptic / @SundareshSankaran: You guys have written numerous custom steps that call SAS Viya services directly from SAS code, anything else you recommend here? For example, is special handling needed for Viya deployment that use certificates or does proc http handle this transparently?
      * @sukckn: If it turns out this requires additional options on proc http, then I'm absolutely fine with not doing that right now and instead simply add a note in readme and about tab in a section called something like "Known restrictions / Ideas for future enhancement". But perhaps proc http handles this transparently? 
      
  * UI - Tab: Output Options 
      *  Just trying to understand why control _httpout is a text field and not an output table control?
      *  Is that because your UI has a checkbox to specify whether the output should be written to a table and then hide/unhide that control? And when using a custom step in flow mode, the step author does not have control to hide/unhide the output port in case you would have used an output table control?  If so, have you ever considered adding a feature request for SAS Studio for this?

  * UI - Tab: About 
      * Typo, "Documantation", should be "Documentation"
      * Change log shows a different "last updated" date then README.md. This date would need updating anyway after you make changes, but can you make sure that About tab and README are in sync?

  * Codegen
    * I realize I still need to update **_template.step** to use consistent coding to delete SAS macros and SAS macro variables  using the **nowarn** option. This to remove the need for logic that checks whether the macro or macro variable exists:
        ```
      /***
          Delete user-defined SAS macros and SAS macro variables using nowarn option.
          Using nowarn to prevent warning messages in SAS log in case the item does not exist because
          it is only created conditionally depending on user selections. A valid use case. 
          Using nowarn avoids the need for the step author to add additional logic that first checks whether
          the item exists before trying to delete it.
      ***/
       %symdel mymacrovar1 / nowarn;
       %symdel mymacrovar2 / nowarn;
       ...
       %sysmacdelete mymacro1 / nowarn;
       %sysmacdelete mymacro2 / nowarn;
       ...
        ```
      * You probably based your codegen on the old template, so no need to modify. If your codegen does not create macros or macro variables conditionally, then you would not even need to check for existence nor use the nowarn option. 
      
* README.md
   * HTTP Request tab
      *  Typo in explanation of Payload: "The column name needs to be masked with a leading a tailing at-sign ..." should be "The column name needs to be masked with a leading and tailing at-sign ..." 
      * Change log shows a different "last updated" date then About tab 
      *

**Comment by snlwih** [comment]
@sukckn , I see that you have updated one README.md in the "extras" folder. BUt nothing in the main README.md or the step itself. Are you expecting any action from me at the moment, or is this the first step to incorporate my feedback?

Btw. some additional feedback. Could you please use official SAS product names in all those README files? For example "SAS Intelligent Decisioning" instead of "Intelligent Decisioning".

**Comment by sukckn** [comment]
Hello Wilbram,

I am incorporating your feedback. I will let you know when I am done.

Thanks,

Clemens

**Comment by SundareshSankaran** [comment]
Hi Wilbram and Clemens,  one check I recommend for those who call SAS Viya
services through proc http is that they check (with their platform
administrator) if their environment allows for communication among SAS Viya
services from internal IPs, which is where SAS Studio runs from.  Known as
“north-south” communications,  these are sometimes subject to the platform
administrator’s decision on whether to allow the same or not.  Adding the
pod CIDR (range of IP adresses) to SAS Viya’s ingress allowlist facilitates
this.

**Comment by sukckn** [comment]
Hello Sundaresh,

Thanks for the comment.
I'll make sure to put an appropriate comment in the README and also have the step to give a appropriate error message if it can't execute a SAS Viya service.

Thanks,

Clemens

**Comment by snlwih** [comment]
@sukckn , thanks for all the updates. Didn't see a comment that you were ready for another review, but decided to alrady have a look at the latest version of the step in this pull request. I noticed the following issues. Hopefully quick and easy to fix:

 * About tab and Readme file do not show the same release date 
 * About tab and Readme file do not have a pre-req section
    * You are using controls and/or control properties, like the link control and it has an indent property >1, that require a fairly recent version of SAS Studio. I don't know whether when you use this step in an older release of SAS Studio it generates and errors, but it probably does. Anyway, you definitely need to list a required minimum SAS Studio version number in your prereqs. 
    * Seeing that you have a checkbox in your Settings tab for the user to specify whether hyperlinks should be shown and use that value in the visibility dependency rules for the link control, you are probably aware that default a Viya deployment (EV setting) has rules with a very strict regex for allowed URL patterns that prevent your URL to be shown and results in the following text being displayed to the user "The value specified in the Link control does not meet the validation requirements for your configuration." instead of the URL itself. You might want to add a note in your pre-req section to explain that a SAS Administrator needs to configure their Viya deployment to allow URLs to be displayed using a Link control in a custom step and point them to[ this SAS blog](https://communities.sas.com/t5/SAS-Communities-Library/SAS-Viya-Link-Control-for-Custom-Steps/ta-p/919005) for more details:  

 * I thought you were going to add the feedback from Sundaresh to your About/README around a default Viya deployment rejecting proc http calls to SAS Viya services even if Compute runs in the same enviroment and include a short description to create awareness and pointers to what to do about this. That would be another bullet for the pre-reqs section. 

 * Code generator
   * It looks like your not unassigning fileref PCODE after you proc python has finished as in 
       ```filame PCODE clear;```

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 15OCT2024

**Pull request merged**
