### PR TITLE
DQ Standardize update for ENCAN, FRCAN.  DQ Cluster update to expand to five rules

### PR DESCRIPTION
**Pull request by ArnoldToporowski**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an **X** inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [ X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X ] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [ X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[Toporowski Github Contributor Agreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/10150523/Toporowski.Github.Contributor.Agreement.txt)

### CODE REVIEW

**Comment by snlwih** [comment]
06DEC2022: Starting review
Thanks for providing a self-explanatory title for the pull request.

Did you update the labels in **_DQ - Standardize_** to adhere to the capitalization guidelines? If so, thanks for doing that 😃 I noticed though that all these updated label seem to be missing a colon at the end, could you fix this?

(minor) The description in the readme file for **_DQ - Standardize_** has become longer and has no new line characters, resulting in one big paragraph. To me the sentences almost represent a list of capabilities/features, which is fine if the are only two sentences. But for longer lists a bulleted list could be considered. I realize that this might be my personal preference, so if you are happy with how that section currently looks then leave it as is. 

Am happy to merge once the labels have been updated.

**Comment by ArnoldToporowski** [comment]
Yes, I updated the labels to adhere to the capitalization guidelines.  I didn't notice they were missing the colons though.  That's fixed now.  

I agree the readme file rambles on, so I have fixed that, and the About tab as well, with the bullet points formatting you suggested.

**Comment by ArnoldToporowski** [comment]
for DQ - Clustering, I also fixed the formatting of the readme file and the About tab.

**Comment by snlwih** [comment]
Thanks for updating those labels, formatting the About tabs, and updating the screenshots shown in the readme file.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 08DEC2022

**Pull request merged**
