### PR TITLE
Create SAS program versions under extras directories for all (SS contributor) steps

### PR DESCRIPTION
**Pull request by SundareshSankaran**
…ned by contributor Sundaresh Sankaran

# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

### CODE REVIEW

**Comment by SundareshSankaran** [comment]
@snlwih , request clarification on a point which may have perhaps not been encountered before.

As you might be able to make out from the PR title,  this is more of a "best practice" change, where I have taken steps to expose the SAS code behind all custom steps (where I am a contributor) under an 'extras' folder.   This is not a new practice and I (along with some others) have been following the same for my recent contributions.  This PR is for the purpose of bringing my earlier contributions to the same level.

When it comes to the Change Log,  I'm unsure about whether to update the version number for the same, because the Custom Step as such has undergone no change, it's only the SAS program.   One idea is to update only the README and not the step, but that would create inconsistencies.  Could you let me know what course of action to follow?

**Comment by SundareshSankaran** [comment]
[ContributorAgreement.txt](https://github.com/user-attachments/files/17150269/ContributorAgreement.txt)

**Comment by snlwih** [comment]
Hi Sundaresh (@SundareshSankaran),

Good question. Although not ideal, it seems to make sense to only update the README files as follows: 
 * Add some text and a link to the folder/files with the SAS code (think the HTTP Request step that is currently in review does that)
 * Add a new entry at the top of the change log using a minor version number, like 1.0.1 and mention that the step itself has not been updates, but that some extra files ahve been added for purpose of ...

When you do this, about how many steps (main folders in the GitHub repo) are we talking? Would like the pull requests to be smallish in size, to make review easier and an individual entry in one of the folders not holding up all the others.

Btw. why did you create this question as a pull request instead of creating an Issue?  THe list of issues (https://github.com/sassoftware/sas-studio-custom-steps/issues) has a "New issue" button, which then shows an "Open blank issue" link. In that panel where you  provide title and body text there is a menu on the right-hand-side to add labels, and a "Question" label already exists. Something to keep in mind for future questions that you would like to discuss.

**Comment by SundareshSankaran** [comment]
Hi @snlwih ,

Thanks for your guidance.   

Answering both your questions about scale and a pull request,  this impacts **22** custom step folders covering **29** SAS program files.  But the basic operation is exactly the same, i.e. to create an extras folder and save the SAS program within.  Given your recent reply,  let's also add **22** updated README files to the review mix.

It might be monotonous if you had to review 22 individual Pull Requests (and for me to create the same)  to perform the same review.  So, a request would be to treat as a common PR.  Since I already had the output ready (and checked), I submitted the PR anyways, pending this question.

By the way, I used an automated process to create these folders in one pass.  Happy to explain that tool (among my personal collection) with you offline,  and if you feel it's useful, can provide a link to the same on this repo.

PS: I'm sure you know this, but let me underscore this is a one-time activity :).   Adding the SAS program is a default activity for my recent custom step contributions (and glad to see some other contributions include this practice, hope it spreads)

**Comment by snlwih** [comment]
@SundareshSankaran , sorry trying to do too many things at the same time so forgot to look at the Files changed link at the top of this thread which answers my question. duh.

Have done some "simple spot checks" on some of the files and its looks okay. So am going to merge as-is.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 019OCT2024

**Pull request merged**
