### PR TITLE
Update: bug fix to LLM - Azure OpenAI RAG

### PR DESCRIPTION
**Pull request by SundareshSankaran**
Signed-off-by: SundareshSankaran <sundaresh.sankaran@sas.com>

# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

### CODE REVIEW

**Review by SundareshSankaran — COMMENTED** [review]
Description of the bug fix:  The option to load all PDFs within a folder was missing a required import of a Python package (PyPDFLoader).  Inclusion of the below line resolved the same.

```python
      from langchain_community.document_loaders import PyPDFLoader
```

The bug seems to have emerged from an addition of the 'single PDF', CSV and other import options, which led to this line getting shifted around and out of the 'folder' loop.

"Before" and "After" logs are attached to establish that the fix worked.

**Comment by SundareshSankaran** [comment]
[AFTER - folder import.pdf](https://github.com/user-attachments/files/15672310/AFTER.-.folder.import.pdf)
[BEFORE - folder import.pdf](https://github.com/user-attachments/files/15672312/BEFORE.-.folder.import.pdf)

Before and After files attached to establish successful fix
Contributor agreement attached.
[ContributorAgreement.txt](https://github.com/user-attachments/files/15672323/ContributorAgreement.txt)

**Comment by samiulhq** [comment]
[ContributorAgreement.txt](https://github.com/user-attachments/files/15676271/ContributorAgreement.txt)

**Review by SundareshSankaran — COMMENTED** [review]
Updated date of last change to step, along with adopting semantic version (an acceptable but not mandatory practice) after consultation with admins.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 11JUN2024

**Pull request merged**
