### PR TITLE
DIAP-DAFT-CLOD First Public Release to Public

### PR DESCRIPTION
**Pull request by stephanweigandt**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an **X** inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[contributing_agreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/9561560/contributing_agreement.txt)

### CODE REVIEW

**Comment by stephanweigandt** [comment]
[contributing_agreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/9561509/contributing_agreement.txt)

**Comment by snlwih** [comment]
Currently reviewing the CLOD (Content Listing of Directory) custom step, which is one of the three steps that are part of this pull request. Am in an offline discussion with Stephan about this. Will post summary at later stage.

**Comment by snlwih** [comment]
Have reviewed CLOD entry and the following changes were suggested and implemented:
- When the debug setting is OFF then cleanup "temporary helper" tables at the end of the step
- Added borders around screenshots to improve readability of README.md file
- Added version number and release date to both README.md and the About tab in the step itself
- Added missing newline characters in parts of README.md to improve readability

Next step will be to review the other entries in this pull request.

**Comment by snlwih** [comment]
Have reviewed DIAP entry, here is a quick summary of the changes that were implemented:

- Removed unused references to tools/routines
- Updated README.md to take advantage of Markdown formatting capabilities to increase readability 
- Updated README and custom step to use official SAS terminology for products/components
- Cleanup "helper" tables unless debug-mode is switched on

**Comment by snlwih** [comment]
Have reviewed the DAFT (Dynamic Aggregation From Timeseries entry, here is a quick summary of the changes that were implemented:

- Small cosmetic updates to README.md to take advantage of Markdown features to help improve readability

The README.md shows sample SAS code to create generated timeseries data that can be used to highlight many of the capabilities of this custom step. Great idea!

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 21SEP2022

**Pull request merged**
