### PR TITLE
Updating Azure OCR custom step to version 2.0

### PR DESCRIPTION
**Pull request by jannichorst**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology
[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/14726657/ContributorAgreement.txt)

### CODE REVIEW

**Comment by jannichorst** [comment]
@SundareshSankaran

**Comment by SundareshSankaran** [comment]
[ContributorAgreement.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/14727184/ContributorAgreement.txt)

**Comment by snlwih** [comment]
@jannichorst , noticed that the About tab has two link controls with the same description and URL (pricing). More importantly, as a default Viya deployment does not have http to external sites enabled, 99% of the users will see this error in the About tab: 

_The value specified in the Link control does not meet the validation requirements for your configuration._

Perhaps an idea to add a note at the top of the Documentation section saying "Note: if there are no links shown below, then ask your SAS administrator to go into SAS Environment manager and use the Configuration panel to configure the allowedStepLinks option of the Data Flow service to allow https connections". 

In the README you could have that a very similar note and then point to this [SAS Communities article](https://communities.sas.com/t5/SAS-Communities-Library/SAS-Viya-Link-Control-for-Custom-Steps/ta-p/919005) that shows an example of how to do this.

What do you think?

**Comment by jannichorst** [comment]
@snlwih good points. I implemented all changes in the custom step and the README.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 03APR2024.

**Pull request merged**
