### PR TITLE
V 1.1.1 of the Data Synthesis Steps

### PR DESCRIPTION
**Pull request by AngusLooneySAS**
# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an **X** inside the square brackets, \[X\], that represents your answer. Using the Preview tab you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [x] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [x] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [x] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

### CODE REVIEW

**Comment by AngusLooneySAS** [comment]
Attaching the Contributor form!

[Contributor Agreement-AngusLooneySAS and DuncanBain - 2022-12-21.txt](https://github.com/sassoftware/sas-studio-custom-steps/files/10278456/Contributor.Agreement-AngusLooneySAS.and.DuncanBain.-.2022-12-21.txt)

**Comment by snlwih** [comment]
The About box of the custom step is still mentioning the old release/version number. This needs to be updates so users can report the correct version number when asking questions or reporting issues. I have sent you an updated .step file via email that has fixed this. I've done this by adding a Text field in the About tab (ID: textChangeLog) underneath the Text field that contains the general description info. The textChangeLog shows the same info as in the readme.md, but I used the same date format (ddMMMyyyy) as recommended in the _template folder. 

Noticed that the README is using a different date format than recommended in the _template folder. Have sent you an updated readme.md file via email.

Once you have updated files in your fork and pushed an update, the pull request contents should be updated. I will then merge them.

**Comment by AngusLooneySAS** [comment]
Updated to address date formatting in About.

**Comment by AngusLooneySAS** [comment]
Cool, so, if I've followed correctly, the PR should be updated with a README and Step that address your comments.

If, I've understood correctly, big if...

**Comment by snlwih** [comment]
Looks good.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 23DEC2022

**Comment by AngusLooneySAS** [comment]
Whoopp!

Thanks.

**Pull request merged**
