### PR TITLE
Updated Custom Step: LLM - Azure OpenAI RAG

### PR DESCRIPTION
**Pull request by SundareshSankaran**
Signed-off-by: SundareshSankaran <sundaresh.sankaran@sas.com>

# Please include answers to these questions as part of your pull request

In the GitHub webUI, use the Write tab to modify the Markdown text that is part of the pull request. For each question simply place an X inside the square brackets, \[X\], that represents your answer. Make sure there are no blanks inside the brackets, otherwise MarkDown doesn't render properly. Using the Preview tab while editing this form, you can see the formatted/rendered version of the message.

- **Q1: Confirm that you have the right to submit the code that is being contributed. Please consider the origin of your code and confirm you have the appropriate rights to make the submission subject to the Apache 2.0 license that applies to everything in this repository of custom steps. If so, follow the instructions for the [Contributor Agreement](ContributorAgreement.txt) (which is based on the industry-standard Developer Certificate of Origin (DCO)).**
   - [X] Yes, I have the right to submit the contributed code on behalf of myself, my company, or any other owner of the code. I have also attached my signed copy of the DCO to this message.
   - [ ] No
- **Q2: Confirm that your contribution does not include any personally identifiable information (PII), for example, in any examples used in your README file.**
   - [X] My contribution does NOT include PII data
   - [ ] My contribution includes PII data
- **Q3: Confirm your contribution does not include any encryption or other export-controlled technology.**
   - [X] My contribution does NOT contain encryption or other export-controlled technology
   - [ ] My contribution includes encryption or other export-controlled technology

### CODE REVIEW

**Comment by SundareshSankaran** [comment]
[ContributorAgreement.txt](https://github.com/user-attachments/files/15981683/ContributorAgreement.txt)

**Comment by SundareshSankaran** [comment]
# Minor changes:
- *Added provision for load from pandas DataFrame.* Minimises need to load from source documents all the time.  One more "dataset"-like option in addition to CSV. Paves the way for adding SAS datasets / CAS tables down the line.

# Patch changes:
- *Azure OpenAI version was previously hardcoded, now surfaced in UI.*  User can change this to updated version based on periodic (roughly 6 months) changes to OpenAI versions.  Also, defaults set to current GA version.

**Comment by samiulhq** [comment]
[ContributorAgreement.txt](https://github.com/user-attachments/files/16030146/ContributorAgreement.txt)

**Review by SundareshSankaran — COMMENTED** [review]
# Update - Version 1.3.1 (10JUL2024)

## Minor changes:

* Added provision for load from pandas DataFrame. Minimises need to load from source documents all the time. One more "dataset"-like option in addition to CSV. Paves the way for adding SAS datasets / CAS tables down the line.

* Keeping above point in mind, added SAS dataset as an input table option.  Next up (either within this PR review / later) is an option to allow CAS tables too

## Patch changes:

* Azure OpenAI version was previously hardcoded, now surfaced in UI. User can change this to updated version based on periodic (roughly 6 months) changes to OpenAI versions. Also, defaults set to current GA version.

* Minor edits to README

**Comment by snlwih** [comment]
Just curious why you have many consecutive blocks of code that check if macro variable _aor_error_flag =0?
```
   %if &_aor_error_flag. = 0 %then %do;
     <some statements here>
   %end;

   %if &_aor_error_flag. = 0 %then %do;
     <and more statements here>
   %end;
```

I think I've seen already in previous versions or perhaps in some of your other contributions, that you have a dedicated macro with  a list of checks to assess if Python is available in the compute session and provide the user with very specific warnings/error to help them remediate the issue. Very interesting!

Btw. will merge the step as-is.

**Comment by snlwih** [comment]
SAS Internal Due Diligence Review - COMPLETED on 18JUL2024

**Pull request merged**
